language: android

# https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25

jdk:
  - oraclejdk8

script:
  - ./gradlew check

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native/
    - $HOME/.gradle/daemon/native/
